version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8

    branches:
        only:
          - master

    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v3-npm-deps-{{ checksum "package-lock.json" }}
            - v3-npm-deps-
      
      - run:
          name: Install Dependencies
          command: npm install && sudo npm install -g node-gyp

      - save_cache: 
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
            
          paths:
            - ./node_modules          

      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build
      
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --project=$FIREBASE_ID --token=$FIREBASE_TOKEN