version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8

    branches:
        only:
          - master

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build
      
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --project=$FIREBASE_ID --token=$FIREBASE_TOKEN