backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}{{month}}{{day}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'string',
          default: '2019-00-00',
        }
      - { label: 'Path', name: 'path', widget: 'string', default: '/20190000' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['hoge'] }
      - { label: 'サムネイル', name: 'thumbnail', widget: 'string', default: '../../static/img/' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
